### PR TITLE
fix(headers): remove headers from message json decode

### PR DESCRIPTION
**Pull request by angelfs**
There is an error with this $decodeMessage['header'] because payload have not header.

### CODE REVIEW

**Comment by KonstantinCodes** [comment]
Please just implement your own Decoder like so:
```php
<?php

namespace App\Message;

use Koco\Kafka\Messenger\KafkaMessageDecoderInterface;
use RdKafka\Message;

class MyDecoder implements KafkaMessageDecoderInterface
{
    /**
     * @inheritDoc
     */
    public function decode(Message $message): array
    {
        return [
            'body' => $message->payload,
            'headers' => [
                'type' => TestMessage::class,
                'Content-Type' => 'application/json'
            ]
        ];
    }

    /**
     * @inheritDoc
     */
    public function supports(Message $message): bool
    {
        return $message->topic_name === 'test';
    }
}
```

And tag the service like so:

```yaml
services:
    App\Message\MyDecoder:
        tags: ['koco.messenger_kafka.decoder']
```

**Comment by KonstantinCodes** [comment]
Added this documentation to https://github.com/KonstantinCodes/messenger-kafka#custom-message-formats

**Comment by gennadigennadigennadi** [comment]
@angelfs https://github.com/KonstantinCodes/messenger-kafka/pull/17
Thought this could be interesting for you.

**Comment by KonstantinCodes** [comment]
@angelfs New method is purely using the Symfony Serializer. That's better and more future proof.
Documented here: https://github.com/KonstantinCodes/messenger-kafka#custom-message-formats

**Pull request closed without merging**
