### PR TITLE
Require nyholm/psr7 to have a default psr HTTP client

### PR DESCRIPTION
**Pull request by Kelthan**
With the adding of psr HTTP dependencies used for KafkaRestProxy*, we have the following error in our project : 
> Attempted to load class "Psr17Factory" from namespace "Nyholm\Psr7\Factory".

Would it be possible to add  nyholm/psr7 to composer ?

### CODE REVIEW

**Comment by KonstantinCodes** [comment]
Hey @Kelthan 
the added dependencies on psr actually shouldn't cause this error. I think this is coming up when you require symfony/http-client without also requiring a package that gives you the relevant psr/http-factory services.

I'm trying to make it in a way where his package here is only dependent on the psr interfaces and the developer who implements it, can require the implementation.

For that, there should definitely be documentation in the readme. Currently a WIP

**Comment by Kelthan** [comment]
Hi @KonstantinCodes, thank you for your answer :)
I just wanted to get the current dev-master running but not using the REST proxy.
The error we encountered is maybe a side effect on our project with the adding of PSR interfaces because we should be able to use messenger-kafka without adding PSR implementation if we don't use the REST proxy isn't it ?

I understand your point on each project choosing their own PSR implementation. I will close this PR.

For organizational matters and because we need https://github.com/KonstantinCodes/messenger-kafka/pull/24 on our project, do you have a date in mind for the next release ?

**Comment by KonstantinCodes** [comment]
Cool! I'd like to do another manual testing run today. By Monday we should have the next release out :)

**Comment by Kelthan** [comment]
Hi @KonstantinCodes, hope you're doing well.
Have you any news for the next release ?

**Comment by KonstantinCodes** [comment]
@Kelthan Thanks for waiting, I had to solve a bug in the CI system to merge the refactoring branch.
Just published the release: https://github.com/KonstantinCodes/messenger-kafka/releases/tag/v0.12

**Pull request closed without merging**
